# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  CANGJIE_HOME: "{{.TASKFILE_DIR}}/out"
  VALID_FLAVORS: [debug, release, relwithdebinfo]
  CANGJIE_FLAVOR: '{{.CANGJIE_FLAVOR | default "debug"}}'
  CANGJIE_SDK_VERSION: "1.0.0"
  CANGJIE_COMPILER_DIR: '{{.TASKFILE_DIR}}/cangjie_compiler'
  CANGJIE_RUNTIME_DIR: '{{.TASKFILE_DIR}}/cangjie_runtime/runtime'
  CANGJIE_STD_DIR: '{{.TASKFILE_DIR}}/cangjie_runtime/stdlib'
  CANGJIE_STDX_DIR: '{{.TASKFILE_DIR}}/cangjie_stdx'
  CANGJIE_INTEROP_DIR: '{{.TASKFILE_DIR}}/cangjie_multiplatform_interop'
  CANGJIE_CJPM_DIR: '{{.TASKFILE_DIR}}/cangjie_tools/cjpm'
  CANGJIE_CJEXPLORE_DIR: '{{.TASKFILE_DIR}}/cjexplore'

tasks:
  build:*:
    desc: Build cangjie toolchain
    vars:
      TOOL: '{{index .MATCH 0}}'

    cmds:
      - task: build.cjc
        if: '{{or (eq .TOOL "cjc") (eq .TOOL "all")}}'
      - task: build.runtime
        if: '{{or (eq .TOOL "runtime") (eq .TOOL "all")}}'
      - task: build.std
        if: '{{or (eq .TOOL "std") (eq .TOOL "all")}}'
      - task: build.stdx
        if: '{{or (eq .TOOL "stdx") (eq .TOOL "all")}}'
      - task: build.cjpm
        if: '{{or (eq .TOOL "cjpm") (eq .TOOL "all")}}'
      - task: build.interop:java
        if: '{{or (eq .TOOL "java") (eq .TOOL "all") (eq .LANG "java")}}'
      - task: build.interop:objc
        if: '{{or (eq .TOOL "objc") (eq .TOOL "all") (eq .LANG "objc")}}'
      - task: build.cjexplore
        if: '{{or (eq .TOOL "cjexplore") (eq .TOOL "all")}}'
    requires:
      vars:
        - name: TOOL
          enum: [cjc, runtime, std, stdx, cjpm, cjexplore, interop, java, objc]

  build.cjc:
    desc: Build cangjie compiler
    dir: '{{.CANGJIE_COMPILER_DIR}}'
    cmds:
      - python3 build.py build -t {{.CANGJIE_FLAVOR}} --enable-assert --no-tests --jobs=16 --version {{.CANGJIE_SDK_VERSION}}
      - python3 build.py install --prefix {{.CANGJIE_HOME}}
      - echo "Replacing cjc binary for correct nix dependencies..."
      - cmd: mv {{.CANGJIE_HOME}}/bin/cjc {{.CANGJIE_HOME}}/bin/cjc.bin
        silent: true
      - cmd: |
          echo >{{.CANGJIE_HOME}}/bin/cjc "\
          #!/usr/bin/env fish
          {{.CANGJIE_HOME}}/bin/cjc.bin --link-option \"-I\$GNU_LD\" \$argv"
        silent: true
      - cmd: chmod +x {{.CANGJIE_HOME}}/bin/cjc
        silent: true
    requires:
      vars:
        - name: CANGJIE_FLAVOR
          enum: [debug, relwithdebinfo, release]
  build.runtime:
    desc: Build cangjie runtime
    dir: '{{.CANGJIE_RUNTIME_DIR}}'
    cmds:
      - python3 build.py build -t {{.CANGJIE_FLAVOR}} --version {{.CANGJIE_SDK_VERSION}}
      - python3 build.py install
      - python3 build.py install --prefix {{.CANGJIE_HOME}}
    requires:
      vars:
        - name: CANGJIE_FLAVOR
          enum: [debug, relwithdebinfo, release]

  build.std:
    desc: Build cangjie standard library
    dir: '{{.CANGJIE_STD_DIR}}'
    vars:
      RUNTIME_OUT_DIR: '{{.CANGJIE_RUNTIME_DIR}}/output'
    cmds:
      - python3 build.py build -t {{.CANGJIE_FLAVOR}} --target-lib {{.RUNTIME_OUT_DIR}} --version {{.CANGJIE_SDK_VERSION}}
      - python3 build.py install --prefix {{.CANGJIE_HOME}}
    requires:
      vars:
        - name: CANGJIE_FLAVOR
          enum: [debug, relwithdebinfo, release]

  build.stdx:
    desc: Build cangjie stdx library
    dir: '{{.CANGJIE_STDX_DIR}}'
    cmds:
      - python3 build.py clean
      - python3 build.py build -t {{.CANGJIE_FLAVOR}}
      - python3 build.py install --prefix {{.CANGJIE_HOME}}
    requires:
      vars:
        - name: CANGJIE_FLAVOR
          enum: [debug, relwithdebinfo, release]

  build.cjpm:
    desc: Build cjpm
    dir: '{{.CANGJIE_CJPM_DIR}}'
    cmds:
      - python3 build/build.py build -t {{.CANGJIE_FLAVOR}}
      - python3 build/build.py install --prefix {{.CANGJIE_HOME}}
    requires:
      vars:
        - name: CANGJIE_FLAVOR
          enum: [debug, relwithdebinfo, release]

  build.interop:*:
    desc: Build cangjie interop library
    vars:
      LANG: '{{index .MATCH 0}}'
    dir: '{{.CANGJIE_INTEROP_DIR}}/{{if eq .LANG "java"}}java/build{{end}}'
    cmds:
      - |
        {{if eq .LANG "java"}}
        python3 build.py build -t {{.CANGJIE_FLAVOR}} --target-lib linux_x86_64_cjnative
        python3 build.py install --target linux_x86_64 --prefix {{.CANGJIE_HOME}}
        {{end}}
    requires:
      vars:
        - name: CANGJIE_FLAVOR
          enum: [debug, relwithdebinfo, release]
        - name: LANG
          enum: [java, objc]

  build.cjexplore:
    desc: Build cangjie cjexplore tool
    dir: '{{.CANGJIE_CJEXPLORE_DIR}}'
    cmds:
      - python3 build/build.py build -t {{.CANGJIE_FLAVOR}}
      - python3 build/build.py install --prefix {{.CANGJIE_HOME}}/tools

  clean:*:
    desc: Clean cangjie component build
    vars:
      TOOL: '{{index .MATCH 0}}'
    cmds:
      - echo "Cleaning {{.TOOL}}"
      - task: cleancjc  
        if: '{{or (eq .TOOL "cjc") (eq .TOOL "all")}}'
      - task: cleanruntime 
        if: '{{or (eq .TOOL "runtime") (eq .TOOL "all")}}'
      - task: cleanstd 
        if: '{{or (eq .TOOL "std") (eq .TOOL "all")}}'
      - task: cleanstdx 
        if: '{{or (eq .TOOL "stdx") (eq .TOOL "all")}}'
      - task: cleancjpm 
        if: '{{or (eq .TOOL "cjpm") (eq .TOOL "all")}}'
    requires:
      vars:
        - name: TOOL
          enum: [cjc, runtime, std, stdx, cjpm, interop, java, objc]

  cleancjc:
    desc: Clean cangjie compiler artifacts
    dir: '{{.CANGJIE_COMPILER_DIR}}'
    cmds:
      - python3 build.py clean

  cleanruntime:
    desc: Clean cangjie runtime artifacts
    dir: '{{.CANGJIE_RUNTIME_DIR}}'
    cmds:
      - python3 build.py clean
    
  cleanstd:
    desc: Clean cangjie std artifacts
    dir: '{{.CANGJIE_STD_DIR}}'
    cmds:
      - python3 build.py clean

  cleanstdx:
    desc: Clean cangjie std artifacts
    dir: '{{.CANGJIE_STDX_DIR}}'
    cmds:
      - python3 build.py clean

  cleancjpm:
    desc: Clean cjpm artifacts
    dir: '{{.CANGJIE_CJPM_DIR}}'
    cmds:
      - python3 build/build.py clean


  init.cjexplorte:
    desc: Clone and init cjexplore repo
    dir: '{{ .TASKFILE_DIR }}'
    cmds:
      - git clone https://gitcode.com/iliayar/cjexplore.git
