#!/usr/bin/env fish

# cjinteropbuild
# build interop lib with 

set -l java "java"
set -l objc "objc"
set -l interop_path "$CJ_WORKSPACE/cangjie_multiplatform_interop"
if test $argv[1] = $java
    pushd "$interop_path/java/build"
    python3 build.py build -t $CANGJIE_FLAVOR --target-lib linux_x86_64_cjnative
        or return 1
    python3 build.py install --target linux_x86_64 --prefix $CANGJIE_HOME
        or return 1
    return 0
end

if test $argv[1] = $objc
    pushd "$interop_path/objc/build"
    python3 build.py build --target=linux_x86_64
        or return 1
    python3 build.py install --target=linux_x86_64 --prefix=$CANGJIE_HOME
        or return 1
    return 0
end

echo "Specify target as an argument: $java or $objc"
return 1
