#!/usr/bin/env fish

# cjtest
# test cangjie compiler

set -l cj_test_dir $CJ_WORKSPACE/cangjie_test
set -l cj_tf_dir $CJ_WORKSPACE/cangjie_test_framework
set -l test_cfg $cj_test_dir/testsuites/LLT/configs/cjnative/cjnative_test.cfg
set -l test_list $cj_test_dir/testsuites/LLT/cjnative_testlist

set -l test_tmp_dir $cj_tf_dir/test_temp
set -l logcjtestdir argv/log/cjtest
set -l test_cases $argv[(count argv)]
set -l test_kind "LLT"

if string match '*HLT/*' $test_cases 
    set test_cfg $cj_test_dir/testsuites/HLT/configs/cjnative/cangjie2cjnative_linux_x86_test.cfg
    set test_list $cj_test_dir/testsuites/HLT/testlist
    set test_kind "HLT"
end

rm -rf $test_tmp_dir
rm -rf $logcjtestdir

set -l test_list_opt "--test_list=$test_list"

pushd $CJ_WORKSPACE
echo "Running $test_kind tests..."

echo "command: python3 $cj_tf_dir/main.py --temp_dir=$test_tmp_dir --log_dir=$logcjtestdir --test_cfg=$test_cfg $test_list_opt --fail-verbose -pFAIL -j8 --debug $test_cases"
python3 cangjie_test_framework/main.py --temp_dir=$test_tmp_dir --log_dir=$logcjtestdir --test_cfg=$test_cfg $test_list_opt --fail-verbose -pFAIL -j8 --debug $test_cases 
popd

